version = 0.1

[default.global.parameters]
region = "us-east-2"

[bootstrap.deploy.parameters]
stack_name = "s3nt-bootstrap"
template_file = "bootstrap/template.yaml"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
resolve_s3 = true

[app.build.parameters]
template_file = "app/template.yaml"

[app.deploy.parameters]
stack_name = "s3nt-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# After s3nt-bootstrap exists, replace resolve_s3 with:
# s3_bucket = "<ArtifactBucketName>"
resolve_s3 = true
